### PR TITLE
Fix redis check in health check

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by sbrunner** [comment]
I'm not certain that the good way to fix it, normally it's a good practice to declare all the used environment variable, it make them visible with docker inspect.

**Comment by fredj** [comment]
The problem is that I'm not using redis; `C2C_REDIS_URL` and `C2C_REDIS_SENTINELS` are set to empty string.
In health check we have this code:
```py
redis = os.environ.get(redis_utils.REDIS_SENTINELS_KEY, os.environ.get(redis_utils.REDIS_URL_KEY))
if redis:
  ....
```
The test is passing which is wrong

**Comment by sbrunner** [comment]
Yes, but this can ve updated...

**Comment by fredj** [comment]
The situation is not as described in my previous comment (I was looking at the wrong project):
In my case `C2C_REDIS_URL` is used and the value in set in the project but `REDIS_SENTINELS_KEY` is not set.

**Comment by fredj** [comment]
@sbrunner I've push a new change to only fix the test in health check

**Review by sbrunner — APPROVED** [review]
Looks good but does it completely fix the issue?

**Comment by fredj** [comment]
fixed with #854

**Pull request closed without merging**
