### PR TITLE
Handle THPeligible smaps value

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
@sbrunner , I have strange logs when **compiling** the docker image:

```
 ---> Running in 8a8764862cbb
Installing dependencies from Pipfile.lock (d3e169)…
Failed to load paths: /bin/sh: 1: /root/.local/share/virtualenvs/tmp-XVr6zr33/bin/python: not found

Output: 
Failed to load paths: /bin/sh: 1: /root/.local/share/virtualenvs/tmp-XVr6zr33/bin/python: not found

Output: 
Failed to load paths: /bin/sh: 1: /root/.local/share/virtualenvs/tmp-XVr6zr33/bin/python: not found
```

and
```
Obtaining file:///opt/c2cwsgiutils
Installing collected packages: c2cwsgiutils
  Running setup.py develop for c2cwsgiutils
Successfully installed c2cwsgiutils
Can't list '/usr/lib/python38.zip'
```

**Comment by sbrunner** [comment]
Strange, on my host it's working...

**Comment by gberaudo** [comment]
> Strange, on my host it's working...

Yes the image builds and it seems to work correctly. It is only these logs during the build.

**Comment by gberaudo** [comment]
This is not an essential PR. I will try to find time to rebase it on master then.

**Pull request merged**
