### PR TITLE
Stop rebuilding obsolete releases

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Review by sbrunner — CHANGES_REQUESTED** [review]
It is not acceptable to don't have OS security updates for about 18 months :-/

**Comment by sbrunner** [comment]
See: https://github.com/camptocamp/c2cwsgiutils/blob/master/SECURITY.md

**Comment by gberaudo** [comment]
> It is not acceptable to don't have OS security updates for about 18 months :-/

You are still relying on release_3?

**Comment by sbrunner** [comment]
The  release_2 is used in GMF 2.4 LTS (still in life for about 18 mounth)
And the release_3 in GMF 2.5 (still in life for about 6 mounth)

**Pull request closed without merging**
