### PR TITLE
Disable acceptance test on release 2 and 3

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by gberaudo** [comment]
@sbrunner, what will happen if someone merges some bumps or backport into these branches?

I have not seen a way to seal a branch, perventing any change.

Would it be an option to let users handle the "apt update && apt upgrade" in their projects?

**Comment by sbrunner** [comment]
> I have not seen a way to seal a branch, perventing any change.

We should be able to do changes to apply security updates on Python packages...

> Would it be an option to let users handle the "apt update && apt upgrade" in their projects?

It will not apply on the Python packages...

**Comment by gberaudo** [comment]
Then it looks very dangerous to remove acceptance in the CI.

But maybe it is a risk the users of release_2 and release_3 are OK to take?
@fredj, are we still using these old releases in our projects?

**Comment by fredj** [comment]
> @fredj, are we still using these old releases in our projects?

we are using release 4 everywhere now

**Comment by sbrunner** [comment]
> Then it looks very dangerous to remove acceptance in the CI.

Yes, it true we should be careful with that. In fact, we should only change the dependencies when we have a security issue

> But maybe it is a risk the users of release_2 and release_3 are OK to take?

I think that better than disable the audit and rebuild.

> we are using release 4 everywhere now

Then it's only GeoMapFish that use those releases :-)

**Comment by sbrunner** [comment]
Looks to working again ...

**Pull request closed without merging**
